
kafka:
  bootstrapServers: 10.128.6.188:32771
  maxBlockMs: 5000
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  topic: alert


consumers:
  - name: KafkaConsumerExample
    bootstrapServers: 10.128.6.188:32771
    groupId: sampleConsumer
    autoCommit: true
    autoCommitIntervalMs: 10000
    sessionTimeoutMs: 30000
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    topic: alert

stream:
  bootstrapServers: 10.128.34.238:9092
